const K='fincoob_app_v2',T='cf_theme',OLD='cf_v1_transactions';
const cats=['Alimentação','Transporte','Moradia','Saúde','Educação','Lazer','Compras','Assinaturas','Cartão de crédito','Salário','Freelance','Outros'].map((n,i)=>({id:'c'+i,name:n,type:i>8&&i<11?'receita':i==11?'ambos':'despesa',isDefault:true}));
const pays=['Pix','Dinheiro','Cartão de débito','Cartão de crédito','Transferência','Boleto','Outro'];
let db={user:'',theme:'light',categories:cats,transactions:[],goals:[],budgets:[]},charts={};
const $=id=>document.getElementById(id),brl=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}),today=()=>new Date().toISOString().slice(0,10),mon=d=>String(d||today()).slice(0,7),uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+''+Math.random(),esc=s=>String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m])),val=v=>Number(String(v||'').replace(/\./g,'').replace(',','.'));
const fmt=v=>{let d=String(v||'').replace(/\D/g,'');return d?(Number(d)/100).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2}):''};
function load(){try{db={...db,...JSON.parse(localStorage.getItem(K)||'{}')}}catch{};if(!db.transactions.length){try{db.transactions=(JSON.parse(localStorage.getItem(OLD)||'[]')||[]).map(x=>({id:x.id||uid(),type:x.type,description:x.descricao||x.description||x.categoria||'Lançamento',amount:Number(x.valor||x.amount),date:x.data||x.date,category:x.categoria||x.category||'Outros',payment:x.payment||'Outro',note:x.note||''})).filter(x=>x.type&&x.date&&x.amount>0)}catch{}};db.categories=db.categories?.length?db.categories:cats;save()}
function save(){localStorage.setItem(K,JSON.stringify(db));localStorage.setItem(T,db.theme||'light')}
function toast(t,c='success'){let e=$('toast');e.textContent=t;e.className='toast '+c;clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.add('hidden'),3000)}
function theme(t){db.theme=t;document.documentElement.classList.toggle('theme-dark',t=='dark');$('btnTheme').innerHTML=`<span class='theme-dot'></span><span>${t=='dark'?'Tema escuro':'Tema claro'}</span>`;save();drawCharts()}
function init(){load();$('userName').value=db.user||'';$('transactionDate').value=today();$('goalDeadline').value=today();$('budgetMonth').value=mon();$('reportStart').value=mon()+'-01';$('reportEnd').value=today();bind();theme(db.theme||'light');render()}
function bind(){document.querySelectorAll('.nav-link').forEach(b=>b.onclick=()=>view(b.dataset.view));document.querySelectorAll('[data-go-view]').forEach(b=>b.onclick=()=>view(b.dataset.goView));$('btnTheme').onclick=()=>theme(db.theme=='dark'?'light':'dark');$('btnSaveUser').onclick=()=>{db.user=$('userName').value.trim();save();toast('Usuário salvo')};$('transactionForm').onsubmit=saveTx;$('transactionForm').onreset=()=>setTimeout(resetTx);$('btnCancelTransactionEdit').onclick=resetTx;document.querySelectorAll('[name=transactionType]').forEach(i=>i.onchange=opts);$('transactionsTable').onclick=txAct;['filterText','filterType','filterCategory','filterStart','filterEnd'].forEach(i=>$(i).oninput=table);$('btnClearFilters').onclick=()=>{['filterText','filterType','filterCategory','filterStart','filterEnd'].forEach(i=>$(i).value='');table()};$('categoryForm').onsubmit=saveCat;$('categoryList').onclick=catAct;['transactionAmount','goalTarget','goalCurrent','budgetLimit'].forEach(i=>$(i).oninput=e=>{e.target.value=fmt(e.target.value);e.target.selectionStart=e.target.selectionEnd=e.target.value.length});['reportStart','reportEnd','reportType','reportCategory','reportPayment'].forEach(i=>$(i).oninput=reports);$('goalForm').onsubmit=saveGoal;$('btnCancelGoalEdit').onclick=resetGoal;$('goalsList').onclick=goalAct;$('goalSuggestion').onclick=e=>{if(e.target.dataset.use&&window.sug){db.goals.push(window.sug);save();goals();toast('Meta criada')}};$('budgetForm').onsubmit=saveBudget;$('budgetMonth').oninput=budget;$('budgetList').onclick=e=>{let b=e.target.closest('[data-del]');if(b&&confirm('Remover orçamento?')){db.budgets=db.budgets.filter(x=>x.id!=b.dataset.del);save();budget()}};$('btnExportJson').onclick=exportJson;$('btnExportAllExcel').onclick=exportExcel;$('btnExportReport').onclick=exportReport;$('btnExportWord').onclick=exportWord;$('backupImport').onchange=importJson;$('btnClearData').onclick=()=>{if(confirm('Apagar todos os dados?')){let th=db.theme;db={user:'',theme:th,categories:cats,transactions:[],goals:[],budgets:[]};save();render()}}}
function view(v){document.querySelectorAll('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.view==v));document.querySelectorAll('.view').forEach(s=>s.classList.toggle('active',s.id=='view-'+v));render()}
function opts(){let t=document.querySelector('[name=transactionType]:checked')?.value||'receita',o=db.categories.filter(c=>c.type==t||c.type=='ambos').map(c=>`<option>${esc(c.name)}</option>`).join(''),all=db.categories.map(c=>`<option>${esc(c.name)}</option>`).join('');$('transactionCategory').innerHTML='<option value="">Selecione</option>'+o;$('filterCategory').innerHTML=$('reportCategory').innerHTML='<option value="">Todas as categorias</option>'+all;$('budgetCategory').innerHTML='<option value="">Categoria de despesa</option>'+db.categories.filter(c=>c.type!='receita').map(c=>`<option>${esc(c.name)}</option>`).join('');$('reportPayment').innerHTML='<option value="">Todas as formas</option>'+pays.map(p=>`<option>${p}</option>`).join('');$('categoryList').innerHTML=db.categories.map(c=>`<div class='tag-item'><div><strong>${esc(c.name)}</strong> <span class='pill'>${c.type}</span></div><div>${c.isDefault?'<span class=pill>Padrão</span>':`<button class=mini-btn data-edit-cat='${c.id}'>Editar</button><button class=mini-btn data-del-cat='${c.id}'>Remover</button>`}</div></div>`).join('')}
function saveCat(e){e.preventDefault();let id=$('categoryId').value,n=$('categoryName').value.trim(),t=$('categoryType').value;if(!n)return toast('Informe a categoria','error');let c=id&&db.categories.find(x=>x.id==id);if(c){let old=c.name;c.name=n;c.type=t;db.transactions.forEach(x=>{if(x.category==old)x.category=n})}else db.categories.push({id:uid(),name:n,type:t,isDefault:false});$('categoryForm').reset();$('categoryId').value='';save();render()}
function catAct(e){let ed=e.target.dataset.editCat,del=e.target.dataset.delCat;if(ed){let c=db.categories.find(x=>x.id==ed);$('categoryId').value=c.id;$('categoryName').value=c.name;$('categoryType').value=c.type}if(del&&confirm('Remover categoria?')){let c=db.categories.find(x=>x.id==del);db.transactions.forEach(x=>{if(x.category==c.name)x.category='Outros'});db.categories=db.categories.filter(x=>x.id!=del);save();render()}}
function saveTx(e){e.preventDefault();let id=$('transactionId').value,a=val($('transactionAmount').value),x={id:id||uid(),type:document.querySelector('[name=transactionType]:checked').value,description:$('transactionDescription').value.trim(),amount:a,date:$('transactionDate').value,category:$('transactionCategory').value,payment:$('transactionPayment').value,note:$('transactionNote').value.trim()};if(!x.description||!x.date||!x.category||!x.payment||!(a>0))return toast('Revise os campos obrigatórios','error');db.transactions=id?db.transactions.map(y=>y.id==id?x:y):[...db.transactions,x];save();resetTx();render()}
function resetTx(){$('transactionForm').reset();$('transactionId').value='';$('transactionDate').value=today();$('typeReceita').checked=true;$('transactionFormTitle').textContent='Novo lançamento';$('btnCancelTransactionEdit').classList.add('hidden');opts()}
function txAct(e){let b=e.target.closest('[data-action]');if(!b)return;let x=db.transactions.find(y=>y.id==b.dataset.id);if(b.dataset.action=='edit-transaction'){$('transactionId').value=x.id;$(x.type=='receita'?'typeReceita':'typeDespesa').checked=true;opts();$('transactionDescription').value=x.description;$('transactionAmount').value=fmt(x.amount*100);$('transactionDate').value=x.date;$('transactionCategory').value=x.category;$('transactionPayment').value=x.payment;$('transactionNote').value=x.note||'';$('transactionFormTitle').textContent='Editar lançamento';$('btnCancelTransactionEdit').classList.remove('hidden')}else if(confirm('Excluir lançamento?')){db.transactions=db.transactions.filter(y=>y.id!=x.id);save();render()}}
function rows(){return db.transactions.slice().sort((a,b)=>b.date.localeCompare(a.date))}
function filtered(){let q=$('filterText').value.toLowerCase();return rows().filter(x=>(!q||(`${x.description} ${x.category} ${x.note}`).toLowerCase().includes(q))&&(!$('filterType').value||x.type==$('filterType').value)&&(!$('filterCategory').value||x.category==$('filterCategory').value)&&(!$('filterStart').value||mon(x.date)>=$('filterStart').value)&&(!$('filterEnd').value||mon(x.date)<=$('filterEnd').value))}
function tr(x,act=1){return`<tr><td>${new Date(x.date+'T00:00:00').toLocaleDateString('pt-BR')}</td><td><strong>${esc(x.description)}</strong><br><small>${esc(x.note||'')}</small></td><td><span class='pill ${x.type}'>${x.type}</span></td><td>${esc(x.category)}</td><td>${esc(x.payment)}</td><td class='right'>${brl(x.amount)}</td>${act?`<td><button class=mini-btn data-action=edit-transaction data-id='${x.id}'>Editar</button> <button class=mini-btn data-action=delete-transaction data-id='${x.id}'>Excluir</button></td>`:''}</tr>`}
function table(){let r=filtered();$('transactionsTable').innerHTML=r.length?r.map(x=>tr(x)).join(''):`<tr><td colspan=7 class=empty-state>Nenhum lançamento encontrado.</td></tr>`}
function sum(r){let inc=r.filter(x=>x.type=='receita').reduce((s,x)=>s+x.amount,0),exp=r.filter(x=>x.type=='despesa').reduce((s,x)=>s+x.amount,0);return{inc,exp,bal:inc-exp,count:r.length}}
function dash(){let all=sum(db.transactions),cur=sum(db.transactions.filter(x=>mon(x.date)==mon()));$('dashboardMonthLabel').textContent='Resumo de '+mon().split('-').reverse().join('/');$('kpiSaldoAtual').textContent=brl(all.bal);$('kpiReceitas').textContent=brl(all.inc);$('kpiDespesas').textContent=brl(all.exp);$('kpiResultadoMes').textContent=brl(cur.bal);$('kpiTotalLancamentos').textContent=all.count+' lançamentos';$('ultimosLancamentos').innerHTML=rows().slice(0,5).map(x=>`<div class=stack-item><div><strong>${esc(x.description)}</strong><span>${esc(x.category)}</span></div><strong>${brl(x.amount)}</strong></div>`).join('')||'<div class=empty-state>Cadastre seu primeiro lançamento.</div>';let top=catTotals();$('topCategorias').innerHTML=top.map((x,i)=>`<div class=rank-item><strong>${i+1}. ${esc(x.category)}</strong><strong>${brl(x.total)}</strong></div>`).join('')||'<div class=empty-state>Sem despesas.</div>';$('dicasFinanceiras').innerHTML=`<article class=tip-card><p>${top[0]?`Maior gasto: ${top[0].category}. Reduzir 10% economizaria ${brl(top[0].total*.1)}.`:'Cadastre despesas para receber dicas automáticas.'}</p></article>`;drawCharts()}
function catTotals(){let m={};db.transactions.filter(x=>x.type=='despesa'&&mon(x.date)==mon()).forEach(x=>m[x.category]=(m[x.category]||0)+x.amount);return Object.entries(m).map(([category,total])=>({category,total})).sort((a,b)=>b.total-a.total)}
function chart(n,c){if(!window.Chart||!$(n))return;if(charts[n])charts[n].destroy();charts[n]=new Chart($(n),c)}
function drawCharts(){let months=[...new Set(db.transactions.map(x=>mon(x.date)))].sort();if(!months.length)months=[mon()];let inc=months.map(m=>sum(db.transactions.filter(x=>mon(x.date)==m)).inc),exp=months.map(m=>sum(db.transactions.filter(x=>mon(x.date)==m)).exp),top=catTotals();chart('chartReceitasDespesas',{type:'bar',data:{labels:months,datasets:[{label:'Receitas',data:inc,backgroundColor:'#059669'},{label:'Despesas',data:exp,backgroundColor:'#dc2626'}]},options:{responsive:true,maintainAspectRatio:false}});chart('chartCategorias',{type:'doughnut',data:{labels:top.map(x=>x.category),datasets:[{data:top.map(x=>x.total)}]},options:{responsive:true,maintainAspectRatio:false}});chart('chartSaldo',{type:'line',data:{labels:months,datasets:[{label:'Saldo',data:months.map((m,i)=>inc[i]-exp[i]),borderColor:'#2563eb'}]},options:{responsive:true,maintainAspectRatio:false}})}
function reports(){let r=rows().filter(x=>(!$('reportStart').value||x.date>=$('reportStart').value)&&(!$('reportEnd').value||x.date<=$('reportEnd').value)&&(!$('reportType').value||x.type==$('reportType').value)&&(!$('reportCategory').value||x.category==$('reportCategory').value)&&(!$('reportPayment').value||x.payment==$('reportPayment').value)),s=sum(r);$('reportReceitas').textContent=brl(s.inc);$('reportDespesas').textContent=brl(s.exp);$('reportSaldo').textContent=brl(s.bal);$('reportCount').textContent=s.count;$('reportTable').innerHTML=r.length?r.map(x=>tr(x,0)).join(''):`<tr><td colspan=6 class=empty-state>Nenhum dado encontrado.</td></tr>`;drawCharts()}
function saveGoal(e){e.preventDefault();let gid=$('goalId').value,g={id:gid||uid(),name:$('goalName').value.trim(),target:val($('goalTarget').value),current:val($('goalCurrent').value),deadline:$('goalDeadline').value,description:$('goalDescription').value};if(!g.name||!(g.target>0)||g.current<0)return toast('Revise a meta','error');db.goals=gid?db.goals.map(x=>x.id==gid?g:x):[...db.goals,g];save();resetGoal();goals()}
function resetGoal(){$('goalForm').reset();$('goalId').value='';$('goalDeadline').value=today()}
function goals(){let top=catTotals()[0];window.sug=top?{id:uid(),name:'Economizar em '+top.category,target:top.total*.1,current:0,deadline:today(),description:'Reduzir 10% dos gastos.'}:null;$('goalSuggestion').innerHTML=window.sug?`<p>Sugestão: economizar ${brl(window.sug.target)} em ${esc(top.category)}.</p><button class='btn primary' data-use=1>Usar sugestão</button>`:'<div class=empty-state>Cadastre despesas para receber sugestão.</div>';$('goalsList').innerHTML=db.goals.map(g=>`<article class=goal-card><strong>${esc(g.name)}</strong><div class=progress><span style='width:${Math.min(100,g.current/g.target*100)}%'></span></div><p>Faltam ${brl(Math.max(0,g.target-g.current))}</p><button class=mini-btn data-del-goal='${g.id}'>Excluir</button></article>`).join('')||'<div class=empty-state>Nenhuma meta cadastrada.</div>'}
function goalAct(e){let del=e.target.dataset.delGoal;if(del&&confirm('Excluir meta?')){db.goals=db.goals.filter(g=>g.id!=del);save();goals()}}
function saveBudget(e){e.preventDefault();let b={id:uid(),category:$('budgetCategory').value,month:$('budgetMonth').value,limit:val($('budgetLimit').value)};if(!b.category||!b.month||!(b.limit>0))return toast('Revise o orçamento','error');db.budgets=db.budgets.filter(x=>!(x.category==b.category&&x.month==b.month));db.budgets.push(b);save();budget()}
function budget(){let m=$('budgetMonth').value,r=db.budgets.filter(b=>b.month==m).map(b=>({...b,spent:db.transactions.filter(x=>x.type=='despesa'&&x.category==b.category&&mon(x.date)==m).reduce((s,x)=>s+x.amount,0)}));$('budgetList').innerHTML=r.map(b=>`<article class='budget-item ${b.spent>=b.limit?'over':b.spent>=b.limit*.8?'warning':''}'><strong>${esc(b.category)}</strong><p>${brl(b.spent)} de ${brl(b.limit)}</p><div class=progress><span style='width:${Math.min(100,b.spent/b.limit*100)}%'></span></div><button class=mini-btn data-del='${b.id}'>Remover</button></article>`).join('')||'<div class=empty-state>Defina um orçamento.</div>'}
function expRows(r){return r.map(x=>({Data:x.date,Descricao:x.description,Tipo:x.type,Categoria:x.category,Pagamento:x.payment,Valor:x.amount,Observacao:x.note}))}
function exportExcel(){if(!window.XLSX)return toast('Excel indisponível','error');let wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(expRows(db.transactions)),'Lancamentos');XLSX.writeFile(wb,'fincoob-dados.xlsx')}
function exportReport(){if(!window.XLSX)return toast('Excel indisponível','error');let wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(expRows(rows())),'Relatorio');XLSX.writeFile(wb,'fincoob-relatorio.xlsx')}
function exportJson(){download(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),'fincoob-backup.json')}
async function importJson(e){let f=e.target.files[0];if(!f)return;try{let j=JSON.parse(await f.text());db={...db,...j};save();render();toast('Backup importado')}catch(err){toast('JSON inválido','error')}}
function exportWord(){download(new Blob(['<html><meta charset=UTF-8><body><h1>Relatório Fincoob</h1><table border=1>'+rows().map(x=>`<tr><td>${x.date}</td><td>${esc(x.description)}</td><td>${brl(x.amount)}</td></tr>`).join('')+'</table></body></html>'],{type:'application/msword'}),'fincoob-relatorio.doc')}
function download(blob,name){let u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),500)}
function render(){opts();dash();table();reports();goals();budget()}
window.addEventListener('DOMContentLoaded',init);
